#ifndef __MyProject1MyFrame3__
#define __MyProject1MyFrame3__

/**
@file
Subclass of MyFrame3, which is generated by wxFormBuilder.
*/

#include "gui.h"

//// end generated include

/** Implementing MyFrame3 */
class MyProject1MyFrame3 : public MyFrame3
{
	public:
		/** Constructor */
		MyProject1MyFrame3( wxWindow* parent );
	//// end generated class members

};

#endif // __MyProject1MyFrame3__
