#ifndef __MyProject1MyFrame2__
#define __MyProject1MyFrame2__

/**
@file
Subclass of MyFrame2, which is generated by wxFormBuilder.
*/

#include "gui.h"

//// end generated include

/** Implementing MyFrame2 */
class MyProject1MyFrame2 : public MyFrame2
{
protected:
	// Handlers for MyFrame2 events.
	void closeInfo(wxCommandEvent& event);
public:
	/** Constructor */
	MyProject1MyFrame2(wxWindow* parent);
	//// end generated class members


};

#endif // __MyProject1MyFrame2__
