#ifndef __MyProject1MyFrame1__
#define __MyProject1MyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "gui.h"

//// end generated include

/** Implementing MyFrame1 */
class MyProject1MyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void openFrames( wxCommandEvent& event );
	public:
		/** Constructor */
		MyProject1MyFrame1( wxWindow* parent );
	//// end generated class members

};

#endif // __MyProject1MyFrame1__
